services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./:/var/www/html
    networks:
      - app-network

  mysql:
      image: mysql:latest
      container_name: mysql_db
      environment:
          MYSQL_ROOT_PASSWORD: api_root
          MYSQL_DATABASE: api_flashcard_db
          MYSQL_USER: user
          MYSQL_PASSWORD: user_password
      ports:
          - "3306:3306"
      volumes:
          - mysql_data:/var/lib/mysql
      networks:
          - app-network
      restart: unless-stopped

  webserver:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./laravel:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
